### PR TITLE
Fix: Dying in Haste mode offsets future event logs

### PR DESCRIPTION
**Pull request by the-remeko**
Due to Haste mode, whenever a player dies, more time is added to the round. Whenever more time is added to the round, all logs after that use the new TimeLeft. If more events happened within InProgressSecsPerDeath, the timestamps of those events would be before the events above them.

I made the event log start at 0 using a TimeSinceStart variable that isn't affected by the death time bonus. Since the round ended event is run after the state is changed, I needed to save the last state to get to its TimeSinceStart.

I think starting the logs at 0 also makes it easier for players to understand when things happened during a round.

### CODE REVIEW

**Comment by mzegar** [comment]
Would it be possible to track how much extra time is added, then simply loop through all the events and add the offset? 

`UI.GeneralMenu.SendSummaryData( EventInfo.Serialize( Events.ToArray() ) );` I think technically here the `ToArray()` does an iteration over the entire events list.

**Comment by kolexxx** [comment]
Good catch. There are better ways to do this:

- Base the time of all the events according to the time of the first logged event, which will always be the round start.
- Keep a `TimeSince` variable in the `EventLogger` class instead of having it be in every `BaseState` instance.

Revert your `BaseState` changes and start from the above two.

**Comment by kolexxx** [comment]
Should we start from 0 or not? @mzegar

**Comment by mzegar** [comment]
> Should we start from 0 or not? @mzegar 

Yeah I think from 0 probably makes more sense

**Comment by kolexxx** [comment]
Thank you for contributing

**Pull request merged**
